### PR TITLE
Add push_notification method to base handler

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by acrellin** [comment]
Will update skyportal accordingly when this is merged.

**Comment by stefanv** [comment]
Would be nice to add a test for this in Baselayer.  Otherwise :+1: .

**Comment by acrellin** [comment]
We don't currently have any testing set up for baselayer, do we?  I can add
a corresponding test to skyportal.

**Comment by stefanv** [comment]
I think we do. It's supposed to deploy the test application.

**Pull request merged**
