### PR TITLE
keep track of when db-mapped entities are modified

### PR DESCRIPTION
**Pull request by dannygoldstein**
I added a column to `models.Base` that keeps track of when any ORM-mapped entity is modified. This will complement the `created_at` field for keeping track of the provenance of objects and data.

### CODE REVIEW

**Comment by dannygoldstein** [comment]
ready for review

**Comment by dannygoldstein** [comment]
requesting that this be merged

**Comment by acrellin** [comment]
@dannygoldstein please resolve merge conflicts

**Comment by stefanv** [comment]
I'm happy with this change. A merge into this branch would be fine.

**Comment by dannygoldstein** [comment]
done

**Pull request merged**
