### PR TITLE
require python 3.7

### PR DESCRIPTION
**Pull request by dannygoldstein**

### CODE REVIEW

**Comment by dannygoldstein** [comment]
travis uses python 3.6

**Comment by dannygoldstein** [comment]
ready for merge

**Comment by acrellin** [comment]
@dannygoldstein you'll need to update .travis.yml in skyportal, too, when you pin it to this commit

**Comment by dannygoldstein** [comment]
This request is due to https://github.com/fritz-marshal/fritz/pull/5#issuecomment-627553048

**Pull request merged**
