### PR TITLE
Do not log 404s from HEAD requests

### PR DESCRIPTION
**Pull request by acrellin**
Closes https://github.com/skyportal/skyportal/issues/1164

### CODE REVIEW

**Comment by stefanv** [comment]
Is there a matching BL part to this?

**Comment by acrellin** [comment]
@stefanv this *is* a BL PR 😉

**Comment by stefanv** [comment]
:joy: OK, then I think it's not quite done—the majority of log calls go into the nginx logs?

**Comment by acrellin** [comment]
@stefanv :)  I'm not sure what you mean

**Comment by stefanv** [comment]
I think the log entries are 404 HEAD entries made by nginx.

**Comment by acrellin** [comment]
@stefanv you mean messages like this? `WARNING:tornado.access:400 PUT /api/comment/26238 (127.0.0.1) 14.89ms`

**Comment by stefanv** [comment]
Yes, exactly.

**Comment by acrellin** [comment]
nginx logging level is currently at "info" -- should we bump that to "error" or at least "warn"?

**Comment by stefanv** [comment]
Probably; but I think we'll still run into the 404 HEADs that way.

**Comment by acrellin** [comment]
Nice, there's already a conditional logging check, so I've just updated that to not log 404s -- wanna take another look @stefanv ?

**Comment by stefanv** [comment]
It must log 404's, just not HEAD calls.

**Comment by stefanv** [comment]
:rocket:

**Pull request merged**
