### PR TITLE
rspack

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR moves from webpack to rspack.

### CODE REVIEW

**Comment by stefanv** [comment]
What is the motivation for rspack?

**Comment by mcoughlin** [comment]
A bit faster and slightly more efficient builds. Might discuss this on the iteration call.

**Comment by stefanv** [comment]
I'm on summer leave atm, but happy to discuss soon as I get back.

**Comment by Theodlz** [comment]
closing, in favor of https://github.com/cesium-ml/baselayer/pull/388

**Pull request closed without merging**
