### PR TITLE
User model - Affiliations

### PR DESCRIPTION
**Pull request by Theodlz**
This PR adds affiliations to the user model. The affiliations are stored as a list of strings, which can be displayed on the frontend and used to write scientific papers or circulars for example. 

A WIP PR on SkyPortal : https://github.com/skyportal/skyportal/pull/3092 uses this to display it on the frontend.

### CODE REVIEW

**Comment by Theodlz** [comment]
Hi @profjsb. I renamed the branch affiliations just to make it more clear but that closed the previous PR. I added your suggestion and opened a WIP PR on SkyPortal.

**Review by guynir42 — APPROVED** [review]
Maybe add an example affiliation in the doc string?

**Comment by Theodlz** [comment]
By the way, do you think I could have the permissions to run the GA ?

**Comment by guynir42** [comment]
@stefan can probably add your permissions to the repo.

**Comment by guynir42** [comment]
Note that you will need to add a PR on skyportal with a migration script (and I assume some code to display/edit affiliations somewhere).

**Comment by guynir42** [comment]
> Note that you will need to add a PR on skyportal with a migration script (and I assume some code to display/edit affiliations somewhere).

Sorry I noticed there's already a skyportal PR as well.

**Comment by guynir42** [comment]
@mcoughlin @Theodlz sure but I'm not sure what we need to coordinate. 
If this is ready (and passes skyportal tests) then we should merge it and then have your PR pin this version of baselayer. 
If that is ready then there's no reason not to merge. 
I would be extra careful to make sure the skyportal version correctly migrates the changes in baselayer!

**Comment by mcoughlin** [comment]
@guynir42 ah by coordinate I just meant exactly that, I.e it will require that the SP PR go in so that the migration is in. If it was to get pinned without the migration we would be in trouble.

**Pull request merged**
