### PR TITLE
Add anacron-style job execution

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by acrellin** [comment]
@stefanv this looks great - do we need to add this service to the supervisord config, too?

**Comment by stefanv** [comment]
Err, yes!! Good catch.

**Comment by acrellin** [comment]
@stefanv how difficult would it be to also specify the time of day the job should be run?  E.g., expensive jobs might best be run during non-peak hours

**Comment by stefanv** [comment]
@acrellin Yes, we can add functionality such as "should be run every x hours, but only between time a and time b".

**Pull request merged**
